"use client";

import { useEffect } from "react";

const replacements: Array<[string,string]> = [
  ["Към основното съдържание","Skip to main content"],
  ["Европа · САЩ · Канада","Europe · USA · Canada"],
  ["ПРЕЗЕНТАЦИЯ","PRESENTATION"],
  ["Помощ и поддръжка","Help & Support"],
  ["Помощ","Help"],
  ["АВТОМОБИЛИ","VEHICLES"],
  ["ТЪРГОВЕ НА ЖИВО","LIVE AUCTIONS"],
  ["КАК ДА КУПЯ","HOW TO BUY"],
  ["ТРАНСПОРТ","TRANSPORT"],
  ["ИСТОРИЯ НА МПС","VEHICLE HISTORY"],
  ["ПОДДРЪЖКА","SUPPORT"],
  ["Вход / Профил","Login / Profile"],
  ["Регистрация","Register"],
  ["Търси автомобили","Search vehicles"],
  ["Търси автомобил","Search vehicle"],
  ["Търси","Search"],
  ["Следи текущия търг в реално време","Follow the current auction in real time"],
  ["Начало","Home"],
  ["Инвентар","Inventory"],
  ["Как да купя","How to Buy"],
  ["Транспорт","Transport"],
  ["История на МПС","Vehicle History"],
  ["Профил","Profile"],
  ["Отвори","Open"],
  ["Затвори","Close"],
  ["Назад","Back"],
  ["Запази","Save"],
  ["Сподели","Share"],
  ["Цял екран","Full screen"],
  ["Филтрирай, следи и наддавай.","Filter, watch and bid."],
  ["Зареждаме автомобилите","Loading vehicles"],
  ["Подготвяме актуалните лотове и състояния на търга.","Preparing current lots and auction states."],
  ["Обновяване в реално време","Real-time updates"],
  ["Автомобили от международни търгове","Vehicles from international auctions"],
  ["активни лота","active lots"],
  ["купи сега","buy now"],
  ["live таймер","live timer"],
  ["Всички","All"],
  ["Запази търсенето","Save search"],
  ["Филтри","Filters"],
  ["Филтри за търсене","Search filters"],
  ["Изчисти","Clear"],
  ["Търси в резултатите","Search results"],
  ["Бързи филтри","Quick filters"],
  ["Само LIVE","LIVE only"],
  ["Марка","Make"],
  ["Модел","Model"],
  ["Година","Year"],
  ["Регион","Region"],
  ["Локация","Location"],
  ["Основна повреда","Primary damage"],
  ["Статус на талона","Title status"],
  ["Статус на търга","Auction status"],
  ["Цена","Price"],
  ["Тип превозно средство","Vehicle type"],
  ["Двигател","Engine"],
  ["Скоростна кутия","Transmission"],
  ["Пробег","Mileage"],
  ["Дата на търга","Auction date"],
  ["резултата","results"],
  ["Показани","Showing"],
  ["Препоръчани","Recommended"],
  ["Цена: ниска → висока","Price: low → high"],
  ["Цена: висока → ниска","Price: high → low"],
  ["Година: нови → стари","Year: newest → oldest"],
  ["Година: стари → нови","Year: oldest → newest"],
  ["ПРОДАДЕНО","SOLD"],
  ["ПРОДАВА СЕ НА ЖИВО","LIVE"],
  ["СЛЕДВАЩ ЛОТ","NEXT LOT"],
  ["ОЧАКВА","UPCOMING"],
  ["Повече детайли","More details"],
  ["Продажбата приключи","Sale ended"],
  ["Виж детайлите","View details"],
  ["Текуща ставка","Current bid"],
  ["Начална ставка","Starting bid"],
  ["Следваща оферта","Next bid"],
  ["Следващ лот","Next lot"],
  ["Оферирай","Bid"],
  ["Страница","Page"],
  ["МРЕЖА ENCHEV НА ЖИВО","ENCHEV LIVE NETWORK"],
  ["Наддавай в реално време","Bid in real time"],
  ["СИНХРОНИЗИРАНЕ","SYNCING"],
  ["Изчакване на първи server state","Waiting for initial server state"],
  ["ТЕКУЩ ЛОТ","CURRENT LOT"],
  ["ТЕКУЩА СТАВКА","CURRENT BID"],
  ["Остава","Remaining"],
  ["ГОТОВ ЗА ОФЕРТА","READY TO BID"],
  ["Резултатът от demo офертата идва от server session state.","The demo bid result comes from server session state."],
  ["контрол","control"],
  ["Отвори детайлите на лота","Open lot details"],
  ["Стартира след текущия","Starts after current lot"],
  ["Как работи","How it works"],
  ["офертата се потвърждава през server-session endpoint.","the bid is confirmed through the server-session endpoint."],
  ["Сървърът връща","The server returns"],
  ["и ценова промяна, а интерфейсът само визуализира този резултат.","and a price change, while the interface only displays the result."],
  ["Това остава auctionAuthority=false demo state.","This remains an auctionAuthority=false demo state."],
  ["АУКЦИОННА ОПАШКА","AUCTION QUEUE"],
  ["Следващи лотове","Upcoming lots"],
  ["Всички автомобили","All vehicles"],
  ["Ключови данни за лота","Key lot data"],
  ["Най-важната информация преди офериране","The most important information before bidding"],
  ["проверени полета","verified fields"],
  ["Леки драскотини / козметични следи","Minor scratches / cosmetic marks"],
  ["Състояние, инспекция и произход","Condition, inspection and provenance"],
  ["Подреден преглед на наличните данни и на това какво още не е потвърдено.","A structured view of available data and what is not yet confirmed."],
  ["Състояние","Condition"],
  ["Данни от аукционния лот","Auction lot data"],
  ["Статус на движение","Run status"],
  ["Вторична повреда","Secondary damage"],
  ["Не е посочена","Not specified"],
  ["Инспекция","Inspection"],
  ["Ясно разграничение на провереното","Clear separation of verified data"],
  ["Визуални щети","Visual damage"],
  ["Описани","Documented"],
  ["Механична инспекция","Mechanical inspection"],
  ["Няма свързан доклад","No linked report"],
  ["Диагностика","Diagnostics"],
  ["Произход и документи","Provenance & documents"],
  ["Идентификация и история","Identification & history"],
  ["Провери история на автомобила","Check vehicle history"],
  ["Това е ENCHEV демо представяне на lot данни.","This is an ENCHEV demo presentation of lot data."],
  ["Липсващите външни инспекционни или provenance доклади са означени като непотвърдени, вместо да се показват като факт.","Missing external inspection or provenance reports are marked as unverified instead of being shown as fact."],
  ["История на офертите","Bid history"],
  ["Последни bid събития","Latest bid events"],
  ["преди 12 сек.","12 sec ago"],
  ["преди 21 сек.","21 sec ago"],
  ["преди 1 мин.","1 min ago"],
  ["преди 3 мин.","3 min ago"],
  ["Ориентировъчна цена до България","Estimated transport cost to Bulgaria"],
  ["Дестинация","Destination"],
  ["София, България","Sofia, Bulgaria"],
  ["Варна, България","Varna, Bulgaria"],
  ["Сливен, България","Sliven, Bulgaria"],
  ["Пощенски код","Postal code"],
  ["Ориентировъчен транспорт","Estimated transport"],
  ["работни дни","business days"],
  ["застрахован транспорт","insured transport"],
  ["Подобни автомобили","Similar vehicles"],
  ["Други активни лотове","Other active lots"],
  ["Следваща минимална оферта","Next minimum bid"],
  ["Твоя оферта","Your bid"],
  ["Максимална оферта","Maximum bid"],
  ["Задай max","Set max"],
  ["Минимум","Minimum"],
  ["стойността е локална демо настройка до backend свързването","the value is a local demo setting until backend integration"],
  ["Купи сега","Buy now"],
  ["Ориентировъчни такси","Estimated fees"],
  ["Транспорт от","Transport from"],
  ["Това е визуалният ENCHEV Lot Details flow.","This is the visual ENCHEV Lot Details flow."],
  ["Реалните плащания, identity verification и server-side bid locking ще бъдат вързани към backend етапа.","Real payments, identity verification and server-side bid locking will be connected in the backend stage."],
  ["Към офертата","Go to bid"],
  ["Транспорт от търга до България","Transport from the auction to Bulgaria"],
  ["Един flow за вземане от площадката, вътрешен транспорт, пристанище, международен превоз и доставка до избран град.","One flow for yard pickup, inland transport, port handling, international shipping and delivery to your selected city."],
  ["Изчисли ориентировъчна цена","Calculate estimate"],
  ["Избери автомобил","Select vehicle"],
  ["Аукционна площадка","Auction yard"],
  ["Порт / терминал","Port / terminal"],
  ["България","Bulgaria"],
  ["До адрес","To address"],
  ["Проследяване","Tracking"],
  ["Статус по етапи на доставката","Delivery stage status"],
  ["Документи","Documents"],
  ["Централизирани транспортни документи","Centralized transport documents"],
  ["Застраховане","Insurance"],
  ["Опция според маршрута и превозвача","Option based on route and carrier"],
  ["Един contact point за клиента","One client contact point"],
  ["ОРИЕНТИРОВЪЧЕН КАЛКУЛАТОР","ESTIMATE CALCULATOR"],
  ["Провери маршрут и бюджет","Check route and budget"],
  ["Това е demo калкулатор за интерфейса.","This is a demo calculator for the interface."],
  ["Финалната оферта ще идва от реалните транспортни партньори и конкретния LOT.","The final quote will come from real transport partners and the specific LOT."],
  ["Избираш автомобил","Choose a vehicle"],
  ["Получаваме pickup location","We receive the pickup location"],
  ["Изчисляваме реален маршрут","We calculate the real route"],
  ["Потвърждаваш транспорта","You confirm transport"],
  ["Произход","Origin"],
  ["Тип автомобил","Vehicle type"],
  ["ПЪТЯТ НА АВТОМОБИЛА","VEHICLE JOURNEY"],
  ["От площадката до клиента","From yard to customer"],
  ["Автомобилът се взема от аукционната площадка след освобождаване на лота.","The vehicle is collected from the auction yard after lot release."],
  ["Вътрешен транспорт","Inland transport"],
  ["Превоз до порт, терминал или европейски хъб според държавата.","Transport to a port, terminal or European hub depending on the country."],
  ["Международен превоз","International shipping"],
  ["Контейнер, RoRo или сухопътен транспорт според автомобила и маршрута.","Container, RoRo or road transport depending on the vehicle and route."],
  ["Доставка","Delivery"],
  ["Пристигане в България и последна отсечка до избрания град или адрес.","Arrival in Bulgaria and final-mile delivery to the selected city or address."],
  ["ЧЕСТИ ВЪПРОСИ","FAQ"],
  ["Какво трябва да знаеш","What you need to know"],
  ["Колко време отнема?","How long does it take?"],
  ["Зависи от държавата, площадката, вида превоз и графика на транспорта.","It depends on the country, yard, transport type and schedule."],
  ["Реалният ETA ще се показва за конкретния LOT.","The real ETA will be shown for the specific LOT."],
  ["Цената фиксирана ли е?","Is the price fixed?"],
  ["Не.","No."],
  ["калкулаторът е ориентир.","the calculator is an estimate."],
  ["Финалната цена зависи от pickup location, размери, порт, превозвач и допълнителни такси.","The final price depends on pickup location, dimensions, port, carrier and additional fees."],
  ["Ще виждам ли статуса?","Will I see the status?"],
  ["Да — планираният ENCHEV flow включва статуси pickup, transit, port, shipped, arrived и delivered.","Yes — the planned ENCHEV flow includes pickup, transit, port, shipped, arrived and delivered statuses."],
  ["Провери историята преди да наддаваш","Check the history before you bid"],
  ["VIN, title status, известни щети, пробег и аукционни записи на едно място.","VIN, title status, known damage, mileage and auction records in one place."],
  ["Текущият екран е demo интерфейс; реалните отчети ще се свържат към външен data provider.","The current screen is a demo interface; real reports will connect to an external data provider."],
  ["Провери VIN","Check VIN"],
  ["Demo режим · не извършва реална VIN справка","Demo mode · does not perform a real VIN lookup"],
  ["КАКВО ЩЕ ПОКАЗВА ОТЧЕТЪТ","WHAT THE REPORT WILL SHOW"],
  ["Данни, които помагат при покупка","Data that helps with buying"],
  ["идентификация","identification"],
  ["Марка, модел, година, двигател и factory configuration.","Make, model, year, engine and factory configuration."],
  ["регистрационен статус","registration status"],
  ["и други статуси според наличния източник.","and other statuses depending on the available source."],
  ["Щети и аукционни събития","Damage and auction events"],
  ["Известни damage записи, снимки и предишни аукционни участия, когато са налични.","Known damage records, photos and previous auction appearances when available."],
  ["История на отчетения пробег и сигнали за несъответствия.","Reported mileage history and inconsistency flags."],
  ["Регистрационни събития според държавата и източника на данните.","Registration events based on country and data source."],
  ["Ясни предупреждения при липсваща, спорна или несъвпадаща информация.","Clear warnings for missing, disputed or mismatched information."],
  ["ВЕЧЕ ИМАШ ЛОТ?","ALREADY HAVE A LOT?"],
  ["Провери автомобила и отвори аукционните му детайли.","Check the vehicle and open its auction details."],
  ["Към инвентара","Go to inventory"],
  ["Помощ и поддръжка","Help & Support"],
  ["Една ясна входна точка за въпроси за търсене на автомобили, LIVE търгове, транспорт, история на МПС и работа с профила.","One clear entry point for questions about vehicle search, live auctions, transport, vehicle history and account use."],
  ["Търсене и инвентар","Search & inventory"],
  ["Отиди към автомобилите и използвай филтрите по марка, локация и състояние.","Go to vehicles and use filters by make, location and condition."],
  ["LIVE търгове","Live auctions"],
  ["Отвори отделната LIVE зала и проследи текущия и следващия лот.","Open the dedicated live room and follow the current and next lot."],
  ["Транспорт и история","Transport & history"],
  ["Използвай специализираните ENCHEV маршрути за доставка и проверка на автомобил.","Use ENCHEV's dedicated transport and vehicle-check flows."],
  ["Отвори инвентара","Open inventory"],
  ["РАБОТНО ПРОСТРАНСТВО НА КУПУВАЧА","BUYER WORKSPACE"],
  ["Обзор","Overview"],
  ["Запазени","Saved"],
  ["Моите търгове","My Auctions"],
  ["Бърз достъп","Quick access"],
  ["Следи запазени лотове и търгове от едно място.","Track saved lots and auctions from one place."],
  ["Твоят ENCHEV профил","Your ENCHEV account"],
  ["Следи запазените автомобили и използвай buyer workspace като изходна точка към инвентара и LIVE търговете.","Track saved vehicles and use the buyer workspace as your starting point for inventory and live auctions."],
  ["Търси автомобили","Search vehicles"],
  ["Запазени автомобили","Saved vehicles"],
  ["Следи лотовете, които искаш да сравниш или да отвориш отново преди търга.","Track lots you want to compare or reopen before the auction."],
  ["запазени","saved"],
  ["Състояние","Condition"],
  ["Отвори лота","Open lot"],
  ["зала","room"],
  ["МОИТЕ ТЪРГОВЕ","MY AUCTIONS"],
  ["Единен изглед за лотовете, които следиш, за които наддаваш, водиш или вече са приключили.","One view for lots you watch, bid on, lead or that have ended."],
  ["Отвори LIVE залата","Open live room"],
  ["Наддавам","Bidding"],
  ["Водя","Leading"],
  ["Приключили","Ended"],
  ["ВОДИШ","LEADING"],
  ["Твоята оферта е най-висока","Your bid is highest"],
  ["НАДДАВАШ","BIDDING"],
  ["Нужна е по-висока оферта","A higher bid is needed"],
  ["СЛЕДИШ","WATCHING"],
  ["Още не си наддавал","You have not bid yet"],
  ["ПРИКЛЮЧИЛ","ENDED"],
  ["Търгът е приключил","The auction has ended"],
  ["Финална цена","Final price"],
  ["Детайли","Details"],
  ["Продължи от профила","Continue from your account"],
  ["Продължи към търсенето и намери следващ автомобил или лот.","Continue searching and find your next vehicle or lot."],
  ["Към инвентара","Go to inventory"],
  ["Влез в отделната търгова зала и следи активния лот.","Enter the dedicated auction room and follow the active lot."],
  ["Отвори LIVE","Open live"],
  ["Отвори помощния център за транспорт, история на МПС и работа с платформата.","Open the help center for transport, vehicle history and platform use."],
  ["Отвори помощ","Open help"],
  ["Презентация","Presentation"],
  ["ЕДИН АВТОМОБИЛ.","ONE VEHICLE."],
  ["ЦЕЛИЯТ ПЪТ.","THE WHOLE JOURNEY."],
  ["Към сайта","Go to site"],
  ["Една кола.","One car."],
  ["Безкрайни възможности.","Endless possibilities."],
  ["От първата снимка до ключовете в ръцете ти.","From the first photo to the keys in your hand."],
  ["Пусни презентацията","Play presentation"],
  ["Избираш","Choose"],
  ["Наддаваш","Bid"],
  ["Получаваш","Receive"],
  ["Студио глас","Studio voice"],
  ["Продуктова визия · студио voice · демонстрационни данни","Product vision · studio voice · demo data"],
  ["Приемане","Acceptance"],
  ["Проверка","Inspection"],
  ["Обява","Listing"],
  ["Търг","Auction"],
  ["Плащане","Payment"],
  ["Документи","Documents"],
  ["Доставка","Delivery"],
  ["История","History"],
  ["Пазари","Markets"],
  ["Етапи","Stages"],
  ["Системен прогрес","System progress"],
  ["работят","in progress"],
  ["тест/грешка","test/error"],
  ["липсват","missing"],
  ["Дизайн процес","Design Process"],
  ["Следващ","Next"],
  ["блокер","blocker"],
  ["доказателство","evidence"],
  ["Грешка","Error"],
  ["Правило","Rule"],
  ["Обновено","Updated"]
];

const ordered = [...replacements].sort((a,b)=>b[0].length-a[0].length);
const attrs = ["aria-label","title","placeholder","alt"] as const;

function translateValue(value:string){
  let next=value;
  for(const [from,to] of ordered) next=next.split(from).join(to);
  return next;
}

function translateNode(node:Node){
  if(node.nodeType===Node.TEXT_NODE){
    const parent=(node.parentElement?.tagName||"").toLowerCase();
    if(parent==="script"||parent==="style"||parent==="code"||parent==="pre") return;
    const current=node.nodeValue||"";
    if(/[А-Яа-я]/.test(current)){
      const next=translateValue(current);
      if(next!==current) node.nodeValue=next;
    }
    return;
  }
  if(!(node instanceof Element)) return;
  for(const attr of attrs){
    const current=node.getAttribute(attr);
    if(current&&/[А-Яа-я]/.test(current)){
      const next=translateValue(current);
      if(next!==current) node.setAttribute(attr,next);
    }
  }
  const walker=document.createTreeWalker(node,NodeFilter.SHOW_TEXT);
  let textNode:Node|null;
  while((textNode=walker.nextNode())) translateNode(textNode);
}

export default function EnglishUiEnforcer(){
  useEffect(()=>{
    const run=()=>translateNode(document.body);
    run();
    const observer=new MutationObserver((mutations)=>{
      for(const mutation of mutations){
        if(mutation.type==="characterData") translateNode(mutation.target);
        for(const node of mutation.addedNodes) translateNode(node);
      }
    });
    observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:[...attrs]});
    return()=>observer.disconnect();
  },[]);
  return null;
}
