"use client";

import { useEffect, useMemo, useState } from "react";
import DesignProcess2 from "./DesignProcess2";
import expansionPart1 from "../master-system-expansion-v2/part-1.json";
import expansionPart2 from "../master-system-expansion-v2/part-2.json";
import expansionPart3 from "../master-system-expansion-v2/part-3.json";
import expansionPart4 from "../master-system-expansion-v2/part-4.json";

type Status = "green" | "yellow" | "red";
type Kind = "core" | "test" | "security" | "legal" | "global" | "ai";
type Task = { id: string; label: string; defaultStatus: Status; kind: Kind };
type Phase = { id: string; title: string; tasks: Task[]; wave: number };
type Notes = Record<string, { evidence?: string; blocker?: string; updatedAt?: string }>;
type RawPhase = [string, string, string[]];

const PLAN_VERSION = "1.0 FROZEN";
const EXPANSION_VERSION = "2.0 APPEND-ONLY";
const FINAL_PHASE = "47";

const raw: RawPhase[] = [
  ["00","System definition & invariants",["System scope and boundaries","Actors and permission map","Authoritative components defined","Critical system invariants documented","Non-functional requirements documented","Dependency inventory","Data classification model","Failure assumptions documented","Definition of GREEN acceptance","Final production acceptance criteria"]],
  ["01","Clean foundation",["Private GitHub repo enchev-auctions|green","Clean Next.js + TypeScript base|green","Vercel project enchev-auctions|green","GitHub → Vercel automatic deploy|green","Supabase project","Redis environment","Local / staging / production environments","Environment variable validation","CI lint / typecheck / test / build||test","Web / API / realtime / worker health endpoints||test"]],
  ["02","Architecture & repository",["apps/web","apps/api","apps/realtime","apps/worker","packages/domain","packages/contracts","packages/config","packages/providers","Database migrations structure","Architecture decision records"]],
  ["03","Database & data integrity",["PostgreSQL schema baseline","Migration runner","Staging seed data","UUID identifiers","UTC timestamps everywhere||global","Archival rules","Immutable critical event history","Idempotency keys for critical writes","Transactional outbox","Migration recovery test||test","Foreign-key / unique / check constraints","Index strategy + query-plan verification||test","Connection pooling + statement timeouts","Critical transaction isolation strategy","Auction row-lock strategy","Serialization conflict retry||test","Row-level security policies||security","Point-in-time recovery capability"]],
  ["04","Identity & access",["Supabase Auth","Register / login / logout / recovery","Buyer / Seller / Support / Admin roles","RBAC permission matrix||security","Admin MFA||security","Session revocation||security","Active / restricted / suspended accounts","Privileged-action audit trail||security","Cross-account access tests||test"]],
  ["05","KYC / KYB / eligibility",["KYC provider abstraction","KYB provider abstraction","Verification states","Manual review queue","Buyer eligibility engine","Seller verification workflow","Compliance holds","Verification audit history","Blocked-user enforcement tests||test"]],
  ["06","Vehicle inventory",["Vehicle CRUD","VIN / make / model / trim / year","Engine / fuel / transmission / drivetrain","Odometer model","Condition / damage / run status","Title/document status","Country / region / city / yard||global","Secure image uploads||security","Secure document uploads||security","Data provenance labels","Vehicle version history","Seller submit → Admin review → Publish","Vehicle validation tests||test"]],
  ["07","Marketplace & discovery",["Homepage","Vehicle listing grid","Vehicle detail page","Search by make / model / VIN / lot","Filters","Sorting","Pagination / infinite loading","Upcoming / live / ended views","Responsive mobile UX","SEO metadata / sitemap / canonical URLs","Accessibility baseline||test"]],
  ["08","Auction configuration",["Auction state machine","No-reserve auction","Reserve auction","Seller-approval result path","Buy-now mode","Versioned auction rules","Bid increment table","Pre-bid / live / end timestamps","Immutable auction-start vehicle snapshot","Auction publish validation||test"]],
  ["09","Pre-Bid & Max Bid engine",["Atomic Pre-Bid transaction","Private Max Bid storage||security","Proxy bidding algorithm","Deterministic equal-max priority","Increment boundary validation","Eligibility before bid acceptance","Duplicate-request protection","Private max never exposed||test","Proxy-bid scenario matrix||test","Accepted-bid sequence number","Monotonic bid ordering","Auction-state validation inside transaction","Bid increment validation inside transaction","Serialization-failure retry||test","Same-millisecond bid race test||test","Bid history append-only enforcement||security"]],
  ["10","Live realtime auction",["Persistent WebSocket service","Authenticated WebSocket handshake||security","Auction rooms","Realtime bid events","Current leader event","Outbid event","Server-authoritative timer","Late-bid extension","Reconnect after network drop","Sequence-gap detection","Authoritative state refetch","Browser-clock manipulation test||test","Two-browser synchronization test||test","WebSocket heartbeat / idle timeout","Auth expiry / refresh handling||security","Per-room authorization||security","Slow-client backpressure","Horizontal realtime fanout","Snapshot + delta recovery protocol","Duplicate event handling||test","Realtime event schema versioning","Out-of-order event simulation||test"]],
  ["11","Finalization & winner",["Exactly-once logical close","Close worker","Single authoritative finalizer","Deterministic winner selection","Reserve result","Seller-approval pending result","Unsold result","Immutable final result event","Exceptional void/reversal with reason + audit","Restart during close test||test","Simultaneous final bids test||test","Close lock / lease strategy","Duplicate close-job protection","Missed-close recovery scanner","Scheduler clock-drift handling","Close retry / idempotency","Exact end-boundary bid test||test"]],
  ["12","Notifications",["Notification event model","Email provider abstraction","SMS provider abstraction","Outbid notification","Auction start notification","Auction result notification","Security alerts||security","Notification preferences","Retry / dead-letter handling||test"]],
  ["13","Release, pickup & logistics",["Release state machine","Compliance/document release gates","Pickup authorization","Single-use pickup code||security","Pickup completed event","Transport provider abstraction","Transport request / quote flow","Shipment status events","Release abuse tests||test"]],
  ["14","Admin & operations",["Admin dashboard","User search / review","Verification queue","Vehicle review queue","Auction create/edit/publish controls","Live auction monitor","Release / logistics queue","Support tickets","Complaints / disputes","Evidence freeze","Feature flags","High-risk admin confirmation||security"]],
  ["15","Legal, privacy & transparency",["Terms version registry||legal","Buyer auction rules||legal","Seller terms||legal","Vehicle condition policy||legal","Privacy notice||legal","Cookie consent / preferences||legal","KYC identity notice||legal","Marketplace transparency||legal","AI transparency||legal","Seller-of-record / platform-role display||legal","Country legal launch gate||global","Policy ↔ behavior tests||test"]],
  ["16","Security hardening",["Authorization abuse suite||security","Rate limiting||security","Bot / scripted abuse controls||security","Secure headers||security","CSRF protection where applicable||security","Signed upload URLs||security","Upload type/size validation||security","Secrets management||security","Key rotation procedure||security","Least-privilege provider credentials||security","Dependency vulnerability scanning||security","External penetration test||security","Threat model||security","Trust-boundary review||security","Object-level authorization tests||security","Secret scanning||security","Static code security scanning||security","Dynamic application security testing||security","Software bill of materials||security","WAF / DDoS protection strategy||security"]],
  ["17","Observability & recovery",["Structured logs","Metrics","Distributed traces","Error tracking","Uptime monitoring","Realtime connection metrics","Bid latency metrics","Auction close failure alert","Worker failure alert","Database backups","Restore drill||test","Disaster recovery runbook"]],
  ["18","Load, concurrency & chaos",["10 concurrent bidders||test","50 concurrent bidders||test","100 concurrent bidders||test","500+ bidder stress test||test","Database contention test||test","WebSocket fanout test||test","Reconnect storm test||test","Duplicate-request storm||test","Realtime restart during auction||test","Worker restart during close||test","Redis interruption recovery||test","No winner corruption under load||test","Long-duration soak test||test","Traffic-spike test||test","Slow-client realtime test||test","Database pool exhaustion test||test","Recovery while under load||test"]],
  ["19","Closed pilot",["Create and verify seller||test","Create vehicle + media + documents||test","Admin review + publish||test","Create and verify Buyer A||test","Create and verify Buyer B||test","Pre-Bid scenario||test","Max Bid scenario||test","Live two-buyer auction||test","Late-bid extension||test","Correct winner||test","Release / pickup flow||test","Complaint reconstruction||test","Full audit reconstruction||test","Pilot sign-off: zero critical blockers||test"]],
  ["20","Production providers",["Production KYC/KYB provider","Production email provider","Production SMS provider","VIN/history provider if used","Transport provider if used","Provider timeout/retry tests||test","Provider outage fallback||test"]],
  ["21","International readiness",["CountryProfile configuration model||global","No country-specific hardcoding||global","Locale-aware dates||global","Timezone-aware display||global","BG locale||global","EN locale||global","Translation key architecture||global","Country-specific KYC profile||global","Country-specific legal profile||global","Country-specific document profile||global","Market activation gate||global","Country #2 without core rewrite||global","Regional CDN strategy||global","Regional data/residency review||global","Unicode normalization||global","Locale fallback chain||global","RTL layout capability||global","International names/address/phone models||global","Translation completeness checks||test","Cross-script search tests||test"]],
  ["22","AI-assisted features",["AI isolated from authoritative auction path||ai","Natural-language vehicle search||ai","AI support assistant||ai","AI listing assistant||ai","AI vehicle summary||ai","AI translation assistance||ai","AI output provenance / labels||ai","AI hallucination / unsafe-action tests||test","Visual damage assistant with human review||ai"]],
  ["23","Production launch & ongoing engineering",["Production domain","Production configuration review","Production secrets review||security","Production backup verified||test","Production health dashboard","Incident runbook","First controlled live auction||test","Post-launch error review||test","Regression suite before every release||test","Performance baseline tracked||test","Canary / staged rollout","Production rollback mechanism","Rollback drill||test","Feature-flag kill switch","Maintenance mode","Post-deploy smoke tests||test","Operational status page","Production config drift detection||test"]],
  ["24","API & contracts",["OpenAPI / API specification","API versioning strategy","Request/response schema validation","Standard error envelope","Request correlation ID contract","Pagination/filter/sort contract","Idempotency-key contract","Rate-limit response contract","API endpoint inventory","Deprecation/backward-compatibility policy","Webhooks contract + signatures||security","WebSocket event contract registry","Schema compatibility tests||test","Web/API/provider contract tests||test"]],
  ["25","Testing strategy",["Unit-test strategy","Integration-test strategy","End-to-end test strategy","Contract-test strategy","Property-based test strategy","Deterministic test fixtures","Controlled clock/time-test utilities","Flaky-test policy","Critical-path coverage target","Cross-browser test matrix","Mobile-browser test matrix","Staging smoke suite","Production smoke suite","Failure-injection test harness"]],
  ["26","CI/CD & software supply chain",["Protected main branch","Required PR checks","Preview deployment per change","Staging deployment pipeline","Production approval gate","Deployment concurrency control","Database migration gate","Dependency lockfile enforcement","Dependency review","Secret scanning gate||security","Code scanning gate||security","SBOM generation||security","Build provenance","Environment-scoped CI secrets||security"]],
  ["27","SLO, capacity & resilience",["Critical user-journey SLIs","API availability SLI","Bid acceptance latency SLI","Realtime delivery latency SLI","Reconnect success SLI","Auction finalization success SLI","Initial SLO targets","Error-budget policy","Latency/timeout budgets","Retry budgets","Capacity model","Graceful degradation rules","Load-shedding rules","Scaling runbook"]],
  ["28","Accessibility & device quality",["WCAG 2.2 AA target","Keyboard-only navigation||test","Visible focus states||test","Screen-reader labels||test","Color contrast checks||test","Status not color-only||test","Accessible forms/errors||test","Accessible dialogs/modals||test","Accessible live-auction status||test","Reduced-motion support||test","200% zoom layout||test","Touch-target sizing||test","Desktop browser matrix||test","iOS/Android browser baseline||test"]],
  ["29","Data lifecycle & privacy engineering",["System-wide data inventory","Data classification by sensitivity","Data minimization review","Retention rules per data class","Deletion/anonymization rules","User data export workflow","Legal-hold exceptions||legal","Backup retention alignment","Object-storage lifecycle","PII redaction in logs||security","Sensitive-data access logging||security","Cross-border data-flow inventory||global"]],
  ["30","Operational readiness",["Service ownership map","Runbook: web/API outage","Runbook: realtime outage","Runbook: worker outage","Runbook: database outage","Runbook: Redis outage","Runbook: storage/provider outage","Runbook: data corruption","Runbook: credential compromise||security","Incident severity model","Escalation path / incident commander","Postmortem template","Maintenance/emergency change procedure","Operational readiness review||test"]],
  ["31","International expansion validation",["Country #2 configuration dry run||global","Country #2 locale package||global","Country #2 KYC/legal/document profiles||global","Country #2 provider routing||global","Country #2 data-residency check||global","Country #2 timezone/DST tests||test","Country #2 Unicode/search tests||test","Country activation feature flag||global","Country activation rollback test||test","No core-auction rewrite verification||test","Third-language dry run||test","RTL dry run||test"]],
  ["32","Master plan governance",["Master task IDs immutable","No silent delete/renumber","GREEN requires evidence","GREEN requires passing test where applicable","YELLOW = partial/error/pending verification","RED = not implemented","New discoveries use append-only GAP IDs","Status history/audit trail","Cloud realtime status store","Plan version displayed in UI"]],
  ["33","Buyer workspace, watchlist & alerts",["Persistent watchlist / favorites","Recently viewed vehicles","Saved searches","Saved-search result alerts","My Auctions: Watching","My Auctions: Bidding","My Auctions: Leading","My Auctions: Ended","Realtime multi-auction action panel","Auction schedule / calendar","Starting-soon reminders","Lot queue position / lots-away indicator","Cross-device workspace synchronization","Duplicate notification suppression||test","Watchlist authorization tests||security","Multi-auction realtime consistency test||test"]],
  ["34","Vehicle inspection intelligence",["Structured inspection report schema","Seller condition declaration","Inspector identity + timestamp provenance","Cold-start video","Walk-around video","Engine audio capture","Undercarriage / underside media","Interactive damage map","OBD diagnostic-code capture","Paint / repair measurement fields","Tire condition fields","Glass / lights / interior condition fields","Inspection photo checklist","Media ordering + required-angle validation","Video transcoding / playback pipeline","Inspection media integrity metadata","Inspection report immutable versions","Inspection moderation workflow","AI damage suggestion is non-authoritative||ai","Inspection completeness tests||test"]],
  ["35","Seller listing workflow & Q&A",["Seller listing wizard","Draft autosave","Required-field readiness checklist","Required-media readiness checklist","Seller preview before submit","Vehicle public Q&A thread","Seller verified replies","Additional media attached to answers","Question moderation / abuse controls||security","Immutable Q&A timestamps","Seller live-auction presence state","Inspection / viewing request workflow","Reserve-lowering workflow","Reserve-not-met follow-up state","Listing change history","Republish/review after critical edit","Seller response notification","Seller workflow end-to-end test||test"]],
  ["36","Professional live-auction UX",["Dedicated bidder focus mode","Multi-lot live dashboard","Current lot + next lot panel","Queue / lane position","Lots-away countdown","Server-time sync indicator","Network quality indicator","Connection-loss banner","Automatic reconnect progress","Authoritative resync after reconnect","Stale-state detection and hard refresh","Bid action confirmation state","Bid accepted / rejected reason UX","Outbid realtime UX","Late-extension realtime UX","Multi-tab conflict handling","Keyboard bidding controls","Mobile live-room layout","Accessible live announcements||test","Two-device same-account behavior test||test"]],
  ["37","Auction trust record & reconstruction",["Vehicle activity timeline","Auction rules snapshot visible after close","Vehicle snapshot visible after close","Accepted bid chronology","Extension-event chronology","Final-result chronology","Seller listing-change chronology","Inspection-version chronology","Q&A history preserved","Admin exceptional-action chronology","Internal immutable audit export","Dispute evidence bundle","Correlation IDs in reconstruction","Tamper-evident critical-event hash chain||security","Complete auction reconstruction test||test"]],
  ["38","Search, discovery & personalization",["Exact VIN search","Exact lot-number search","Full-text vehicle search","Faceted filtering","Typo tolerance","Make/model synonym normalization","Transliteration-aware search||global","Cross-script matching||global","Search sort consistency","Index freshness pipeline","Search index rebuild","Search outage fallback","Similar-vehicle recommendations","Recently-viewed recommendations","Saved-filter presets","Search result URL state","Search analytics instrumentation","Search performance baseline||test","Large-catalog search load test||test"]],
  ["39","Real international proof",["Country #1 fully configuration-driven||global","Country #2 fully configuration-driven||global","Country #2 activated without auction-core rewrite||test","Third-language production dry run||test","Timezone + DST correctness||test","Locale date/time formatting||global","Locale number formatting||global","Metric / imperial unit profile||global","International address models||global","International phone models||global","Unicode normalization in all user text||global","RTL UI dry run||test","Locale fallback behavior||test","Country-specific KYC routing||global","Country-specific document profile||global","Country-specific provider routing||global","Regional data-flow/residency verification||global","Country activation rollback||test"]],
  ["40","Production failure certification",["Realtime process crash during active auction||test","Worker crash during active auction||test","Worker crash during finalization||test","Redis connection loss||test","Database connection interruption||test","Object-storage outage||test","KYC provider outage||test","Notification provider outage||test","Client offline/reconnect during bidding||test","Network partition simulation||test","Duplicate event delivery||test","Out-of-order event delivery||test","Sequence-gap recovery||test","Stale-cache recovery||test","Clock-skew simulation||test","Service restart with active rooms||test","No bid-history corruption after failure||test","No winner corruption after failure||test","Failure drill evidence captured"]],
  ["41","Security & abuse certification",["OWASP ASVS control mapping||security","OWASP API Security Top 10 mapping||security","Object-level authorization abuse test||security","Function-level authorization abuse test||security","Authentication brute-force test||security","Session fixation/revocation test||security","Admin MFA enforcement test||security","Privilege-escalation test||security","WebSocket authorization abuse test||security","Replay / duplicate critical-request test||security","Rate-limit bypass test||security","Bot / scripted bidding abuse test||security","SSRF assessment||security","Upload-content attack test||security","Secret scanning clean||security","SAST clean of Critical/High||security","DAST clean of Critical/High||security","Dependency scan clean of Critical/High||security","SBOM produced and archived||security","External penetration test completed||security","All Critical/High findings resolved||security"]],
  ["42","Performance certification",["Production-like performance baseline||test","10 concurrent bidders certified||test","50 concurrent bidders certified||test","100 concurrent bidders certified||test","500+ concurrent bidders certified||test","Bid API p50/p95/p99 recorded||test","Realtime p50/p95/p99 recorded||test","Auction close latency recorded||test","Database lock contention profile||test","Database pool saturation test||test","WebSocket fanout saturation test||test","Reconnect-storm certification||test","Traffic-spike certification||test","Long-duration soak certification||test","Memory-leak observation||test","CPU saturation behavior||test","Horizontal-scale test||test","Load-shedding behavior||test","No data/winner corruption at certified load||test","Launch capacity limit documented"]],
  ["43","Recovery certification",["Automated database backup verified||test","Point-in-time recovery drill||test","Restore into clean environment||test","Critical row-count/integrity verification||test","RPO measured","RTO measured","Accidental-delete recovery drill||test","Corrupted-data recovery scenario||test","Redis/cache rebuild from source of truth||test","Search-index rebuild from source of truth||test","Worker replay/recovery drill||test","Credential rotation drill||security","Provider credential compromise drill||security","Regional outage recovery plan||global","Disaster runbook executed end-to-end||test","Recovery evidence archived"]],
  ["44","Closed production pilot",["Production-grade infrastructure active","Production monitoring/alerts active","Verified test seller onboarded||test","Multiple realistic vehicles published||test","Multiple verified buyers onboarded||test","Pre-bid pilot||test","Max/proxy-bid pilot||test","Live multi-buyer pilot||test","Late-extension pilot||test","Reconnect during pilot||test","Realtime service restart during pilot||test","Worker restart during pilot||test","Deterministic winner verified||test","Notification flows verified||test","Release/pickup/logistics flow verified||test","Support/dispute flow exercised||test","Full audit reconstruction completed||test","Zero Critical blockers at pilot sign-off||test"]],
  ["45","Controlled public launch",["Controlled user cohort / allowlist","Feature-flagged launch","Canary release enabled","Production dashboards watched live","Critical alerts verified","Incident commander/on-call path active","Rollback path immediately available","Kill switch verified","Status page operational","Synthetic critical-journey checks","Daily production error review","Capacity headroom monitored","No unresolved Critical/High launch issue||security","Launch go/no-go checklist completed||test"]],
  ["46","International production launch",["Country #2 production activation||global","Country #2 production locale verified||global","Country #2 timezone/DST verified||test","Country #2 KYC route verified||test","Country #2 document profile verified||test","Country #2 provider routing verified||test","Country #2 support/operations runbook","International end-to-end auction test||test","Cross-country realtime consistency test||test","No auction-core rewrite confirmation||test","Country #2 rollback verified||test","Third-language production smoke test||test","International observability segmentation","International launch sign-off||test"]],
  ["47","FINAL SYSTEM ACCEPTANCE — 100%",["All phases 00–46 GREEN with evidence||test","All critical user journeys pass in production||test","All auction concurrency scenarios pass||test","Winner/finalization invariants proven||test","Realtime reconnect/recovery proven||test","No unresolved Critical/High security findings||security","Backup + restore certification current||test","Performance certification current||test","Failure certification current||test","Closed production pilot signed off||test","Controlled public launch stable||test","Country #2 production proof complete||global","Full auction reconstructable from audit trail||test","Production runbooks complete","Master plan evidence complete","Final 100% acceptance sign-off||test","All appended audit phases 48–61 GREEN with evidence||test","Execution-wave dependency audit complete||test"]],
  ["48","Infrastructure as Code, DNS, TLS & edge",["Infrastructure-as-Code baseline","Reproducible local/staging/production provisioning","Infrastructure state locking / concurrency protection","Infrastructure change review policy","Infrastructure drift detection","DNS ownership and zone inventory","Domain expiration monitoring","DNS change rollback procedure","TLS 1.2+ / TLS 1.3 policy||security","Automated certificate issuance and renewal||security","Certificate expiry alerting||security","HSTS production validation||security","Content-Security-Policy rollout and enforcement||security","CORS allowlist policy||security","WebSocket Origin validation||security","Security-header automated test||test","WAF ruleset baseline||security","DDoS protection strategy verified||security","Edge bot throttling controls||security","Origin bypass protection||security","Outbound egress restrictions / SSRF containment||security","Network and service trust-boundary diagram||security","Staging/production infrastructure parity review||test","Full environment rebuild drill||test"]],
  ["49","Secure data, files & key management",["Encryption-at-rest inventory||security","Encryption-in-transit for external and internal hops||security","KMS / key inventory and ownership||security","Key rotation schedule and procedure||security","Sensitive-field encryption or pseudonymization model||security","Private object-storage by default||security","Signed URL TTL and scope policy||security","Upload quarantine area||security","Malware scanning pipeline||security","Magic-byte / real content-type validation||security","Filename and path sanitization||security","Generated object keys instead of user paths||security","Archive / ZIP bomb rejection||security","Active-content and macro rejection where applicable||security","EXIF / metadata sanitization||security","Image recompression / sanitization pipeline||security","Video transcoding isolation||security","Clean / dirty storage separation||security","Secure download headers||security","Media/document authorization tests||test","Malware-scanner outage behavior||test","Secure deletion verification||test","Key-compromise response runbook||security","Key-rotation drill||test"]],
  ["50","Event, queue & worker correctness",["Canonical event envelope","Globally unique event ID","Event source / type / schema / time / correlation fields","Event schema registry","Backward/forward event compatibility policy","Transactional outbox dispatcher","Outbox backlog metric and alert","At-least-once delivery assumption documented","Idempotent event consumers","Inbox / processed-event deduplication store","Per-auction ordering key","Poison-event dead-letter queue","Exponential backoff + jitter","Maximum retry-attempt policy","Controlled event replay tool","Replay authorization and audit||security","Dead-letter redrive procedure","Worker lease / heartbeat","Job deduplication keys","Consumer lag metrics","Duplicate delivery test||test","Out-of-order delivery test||test","Replay-after-outage test||test","Retry-storm containment test||test","No duplicate side effects test||test"]],
  ["51","Database HA, time authority & zero-downtime data operations",["Database primary/replica topology","Single authoritative write region per hot auction","Read-after-write consistency policy","Replica-lag metrics and alerting","Stale reads forbidden for bid/winner decisions","Read-routing policy","Database failover strategy","Database failover drill||test","Fencing / leader-safety mechanism where required","Connection failover test||test","Zero-downtime migration policy","Expand → migrate/backfill → contract pattern","Backward-compatible schema window","Online index creation strategy","Throttled backfill strategy","Migration lock timeout and safety","Migration roll-forward / rollback decision policy","Schema drift detection","Cache authority matrix","Cache invalidation policy","Redis rebuild from PostgreSQL source of truth||test","Search-index rebuild from source of truth||test","Derived-data reconciliation jobs","Orphan/inconsistency detection","Server/NTP clock source defined","Clock-drift metrics and alerts","Monotonic interval timing rule","Cross-service clock-skew budget","Auction close-boundary time specification","Clock-correction recovery test||test"]],
  ["52","Identity assurance, sessions & privileged access",["Identity assurance level mapping","NIST SP 800-63-4-inspired admin assurance review||security","Admin passkeys / WebAuthn support||security","Phishing-resistant privileged MFA||security","Secure MFA recovery codes||security","MFA reset verification workflow||security","Step-up authentication for high-risk actions||security","Recent-auth requirement for credential/admin changes||security","Secure / HttpOnly / SameSite session-cookie policy||security","Session device inventory","Concurrent-session policy","JWT issuer/audience/algorithm validation||security","JWKS / signing-key rotation handling||security","Authentication rate limits||security","Breached-password screening when passwords are used||security","Credential-stuffing detection||security","Account-recovery abuse tests||test","Email-change confirmation and alert||security","Phone-change confirmation when phone auth is used||security","Credential-change notifications||security","Suspicious-login alerting||security","Privileged-role grant approval workflow||security","Dual control for highest-risk role grants||security","Break-glass admin account||security","Break-glass monitoring and test||test","Dormant privileged-account disabling||security","Session replay/revocation tests||test"]],
  ["53","Auction fraud, abuse & emergency controls",["Auction-specific fraud threat model||security","Shill-bidding / collusion signal model||security","Seller-linked bidder signal detection||security","Multi-account / device relationship signals||security","IP/device velocity controls||security","Suspicious bid-pattern detection||security","Scripted/automated bidding abuse detection||security","Seller manipulation review workflow","Duplicate VIN / duplicate listing detection","Suspicious reused-media detection","Reserve manipulation review workflow","Exceptional bid-cancellation policy and audit","Admin bid-manipulation prevention||security","Result override requires maker-checker approval||security","Pause active auction control","Suspend lot control","Resume auction control","Reschedule auction control","Cancel auction control","Accepted-bid behavior on cancellation defined","Emergency stop / kill switch","Participant notification on exceptional auction changes","Immutable exceptional-action audit trail","False-positive fraud review / appeal path","Post-auction fraud case workflow","Fraud and emergency scenario suite||test"]],
  ["54","Privacy, regulatory & marketplace compliance operations",["Privacy-by-design gate||legal","DPIA applicability decision per risky processing||legal","DPIA workflow when required||legal","Controller/processor role map||legal","Lawful-basis map per data purpose||legal","Records of processing activities / data-processing inventory||legal","Data-subject request identity verification||security","Access/export request workflow||legal","Deletion/anonymization workflow||legal","Restriction/objection workflow where applicable||legal","Personal-data breach detection workflow||security","Breach triage and severity assessment||security","72-hour GDPR notification workflow when applicable||legal","Breach evidence and decision log||legal","Country regulator/contact matrix||global","DPA / subprocessor inventory||legal","Third-party data-location inventory||global","Third-party security/privacy review||security","Third-party exit / data return-delete plan","Cross-border transfer mechanism review||global","DSA applicability assessment||legal","Trader traceability controls when applicable||legal","Consumer/trader status capture where legally required||legal","European Accessibility Act applicability review||legal","Accessibility statement where required||legal","Auction/dealer/marketplace licensing review per country||legal","Sanctions/export-control applicability review per country||legal","Country legal launch sign-off evidence||global","Terms/policy acceptance receipt","Policy-version receipt bound to user/action","Regulatory-change monitoring owner"]],
  ["55","Provider & third-party runtime governance",["Production provider inventory","Owner for every external provider","Sandbox / staging / production provider separation","Signed provider-webhook verification||security","Provider-webhook idempotency","Provider API version pinning","Provider deprecation monitoring","Provider rate-limit / quota inventory","Provider timeout policy","Provider circuit breakers","Provider retry budgets","Provider fallback behavior","Provider outage runbook","Provider status monitoring","Provider credential rotation||security","Least-privilege provider scopes||security","Provider incident-contact path","Provider data export / exit test||test","Backup-provider decision for critical capabilities","Provider contract tests||test"]],
  ["56","Frontend performance, RUM, international SEO & accessibility proof",["Core Web Vitals targets: LCP / INP / CLS||test","Real User Monitoring (RUM)","Synthetic frontend performance monitoring","Frontend performance budget","JavaScript bundle-size budget","Image optimization policy","Font loading / fallback strategy","CDN and cache-header verification","Slow-network browser test||test","Browser JavaScript error telemetry","Hydration/render error monitoring","Locale-specific URL strategy||global","hreflang implementation||global","Localized canonical URLs||global","Locale-aware sitemaps||global","robots.txt and crawl policy","Noindex protection for staging/admin surfaces||security","Localized metadata / social metadata||global","404 / 410 behavior","RUM segmentation by country/device/browser","Automated accessibility gate||test","Manual NVDA screen-reader test||test","Manual VoiceOver test||test","Zoom/touch/responsive manual verification||test","SEO crawl/indexability test||test"]],
  ["57","Messaging integrity & deliverability",["Email sending-domain verification","SPF configuration","DKIM signing","DMARC policy and reporting","Hard/soft bounce handling","Complaint handling","Suppression list","Notification preferences enforced","Transactional vs marketing message separation","Template version registry","Localized message templates||global","Signed/expiring action links||security","Email-provider webhook signature validation||security","Webhook idempotency for delivery events","Delivery-status reconciliation","SMS sender identity / country rules||global","SMS opt-out handling where applicable||legal","SMS delivery receipt handling","Duplicate-notification suppression","Delivery success/failure metrics","Domain reputation monitoring","Critical-security notification priority","Provider failover test||test","Emergency communications fallback test||test"]],
  ["58","Software supply-chain, artifact & license trust",["Dependency lockfile integrity gate||security","Direct dependency pinning policy||security","GitHub Actions / CI action pinning policy||security","Dependency review gate||security","Open-source license inventory||legal","License allow/deny policy||legal","Third-party asset/font/image license inventory||legal","Third-party notices generation||legal","SBOM freshness verification||security","Build provenance generation||security","Signed provenance target aligned with SLSA 1.2||security","Provenance verification deployment gate||security","Release artifact digest / checksum manifest||security","Production artifact-to-commit verification||security","Release manifest","Secret-free build artifact test||test","CI runner hardening review||security","Protected production-environment approvals||security","Artifact tamper-detection test||test","Dependency update / patch policy||security","Vulnerability remediation SLA by severity||security","Rollback artifact retention","Reproducible-build assessment where practical||test","Release signing / attestation archive||security"]],
  ["59","Organization accounts & delegated access",["Individual vs organization account model","Organization profile","Organization ↔ KYB linkage","Organization member invitations","Organization role matrix","Delegated bidding authority","Delegated seller/listing authority","Scoped delegation by market/auction where needed","Invitation expiry and revocation","Member removal revokes active access||security","Organization owner-transfer workflow||security","Organization suspension / restriction","Cross-organization isolation tests||test","Organization audit log","Delegated-action attribution","High-risk delegated-action confirmation||security","Organization account recovery workflow||security","Organization end-to-end authorization tests||test"]],
  ["60","Yard, document & physical chain-of-custody operations",["Yard / branch model","Yard staff role permissions||security","Vehicle physical-location model","Vehicle intake / check-in workflow","Condition-at-intake record","Key custody tracking","Barcode / QR identifier","Yard movement history","Physical custody handoff log","Photo evidence at custody handoff","Pickup appointment workflow","Gate release verification","Pickup identity verification||security","Single-use release-code validation||security","No-release / compliance hold enforcement","Vehicle checkout workflow","Damage-at-pickup evidence workflow","Transport handoff record","Yard connectivity-degraded fallback procedure","Physical inventory audit","Country document-type catalog||global","Document intake workflow","Document authenticity/review state","Seller authority / ownership evidence","Document/title state machine","Missing/invalid document hold","Immutable document versions","Country export-document profile||global","Secure release-document packet","Document chain-of-custody log","Document retention rules","Document-dispute evidence bundle","Yard/document end-to-end test||test"]],
  ["61","Auction events, lanes & auctioneer operations",["Auction event / sale entity","Auction lane entity","Lot sequence / run order","Precomputed lane queue","Parallel lane support","Current-lot / next-lot authoritative state","Lots-away count","Lane pause / resume","Lot skip control","Lot move / reorder control","Lot reschedule workflow","Server-owned lane progression","Auctioneer console","Auctioneer role + step-up auth||security","Seller live-presence state","Start-lot control","Manual extension/pause authority rules","Exceptional auctioneer action audit","Buyer lane synchronization","Multi-lane WebSocket room model","Parallel-lane scale test||test","Lane failover with active auctions||test","Timezone-aware auction scheduling||global","DST scheduling tests||test","Full auction dry-run simulator||test"]]
];

const WAVE_LABELS: Record<number,string> = {
  0:"Definition & governance",
  1:"Engineering foundation & cross-cutting design",
  2:"Core data & reliability infrastructure",
  3:"Identity, security & compliance foundations",
  4:"Vehicle, seller & physical domain",
  5:"Authoritative auction core",
  6:"Realtime, events & communications",
  7:"Product, admin, search & trust surfaces",
  8:"International, accessibility & frontend proof",
  9:"Hardening, security & load certification",
  10:"SLO, operations & recovery certification",
  11:"Closed pre-production pilot",
  12:"Production readiness & closed production pilot",
  13:"Controlled public launch",
  14:"International production expansion & advanced features",
  15:"Final system acceptance"
};

const PHASE_WAVE: Record<string,number> = {
  "00":0,"32":0,
  "01":1,"02":1,"21":1,"24":1,"25":1,"26":1,"48":1,"54":1,"58":1,
  "03":2,"17":2,"49":2,"50":2,"51":2,
  "04":3,"05":3,"15":3,"16":3,"29":3,"52":3,"55":3,
  "06":4,"34":4,"35":4,"59":4,"60":4,
  "08":5,"09":5,"11":5,"53":5,"61":5,
  "10":6,"12":6,"57":6,
  "07":7,"13":7,"14":7,"33":7,"36":7,"37":7,"38":7,
  "28":8,"31":8,"39":8,"56":8,
  "18":9,"41":9,"42":9,
  "27":10,"30":10,"40":10,"43":10,
  "19":11,
  "20":12,"23":12,"44":12,
  "45":13,
  "22":14,"46":14,
  "47":15
};

const frozenPhases: Phase[] = raw.map(([id,title,items]) => ({ id, title, wave: PHASE_WAVE[id] ?? 99, tasks: items.map((entry,index) => {
  const [label,statusRaw,kindRaw] = entry.split("|");
  const defaultStatus: Status = statusRaw === "green" || statusRaw === "yellow" ? statusRaw : "red";
  const validKinds: Kind[] = ["core","test","security","legal","global","ai"];
  const kind: Kind = validKinds.includes(kindRaw as Kind) ? kindRaw as Kind : "core";
  return { id: `${id}.${String(index+1).padStart(2,"0")}`, label, defaultStatus, kind };
}) }));

const expansionParts = [expansionPart1, expansionPart2, expansionPart3, expansionPart4];
const expansionPhases: Phase[] = expansionParts.flatMap((part) => part.phases.map((phase) => ({
  id: String(phase.id),
  title: String(phase.title),
  wave: Number(phase.wave),
  tasks: phase.tasks.map((task,index) => ({
    id: `${phase.id}.${String(index+1).padStart(2,"0")}`,
    label: String(task.label),
    defaultStatus: task.defaultStatus as Status,
    kind: task.kind as Kind
  }))
})));

const phases: Phase[] = [...frozenPhases, ...expansionPhases]
  .sort((a,b)=>a.wave-b.wave || a.id.localeCompare(b.id,undefined,{numeric:true}));

const VERIFIED_EVIDENCE: Record<string,string> = {
  "01.01": "GitHub repository verified: SoulFlameAdmin/enchev-auctions",
  "01.02": "Next.js + TypeScript production build verified on Vercel",
  "01.03": "Vercel project verified: enchev-auctions",
  "01.04": "GitHub main → Vercel automatic production deployment verified"
};

const SK="enchev-system-status-v5", NK="enchev-system-notes-v5", GK="enchev-system-gaps-v5", CK="enchev-system-realtime-v5";
function defaults(){ const out:Record<string,Status>={}; phases.forEach(p=>p.tasks.forEach(t=>out[t.id]=t.defaultStatus)); return out; }

export default function MasterSystemPlanV1(){
  const [menu,setMenu]=useState(false), [open,setOpen]=useState(false), [design2Open,setDesign2Open]=useState(false), [statuses,setStatuses]=useState<Record<string,Status>>(defaults), [notes,setNotes]=useState<Notes>({}), [gaps,setGaps]=useState<Task[]>([]), [filter,setFilter]=useState<"all"|Status>("all"), [query,setQuery]=useState(""), [gapText,setGapText]=useState(""), [now,setNow]=useState(new Date());

  useEffect(()=>{ try{ const s=localStorage.getItem(SK),n=localStorage.getItem(NK),g=localStorage.getItem(GK); if(s)setStatuses(c=>({...c,...JSON.parse(s)})); if(n)setNotes(JSON.parse(n)); if(g)setGaps(JSON.parse(g)); }catch{} },[]);
  useEffect(()=>{ const x=window.setInterval(()=>setNow(new Date()),1000); return()=>window.clearInterval(x); },[]);
  useEffect(()=>{ const c=new BroadcastChannel(CK); c.onmessage=e=>{ if(e.data?.type!=="state")return; if(e.data.statuses)setStatuses(x=>({...x,...e.data.statuses})); if(e.data.notes)setNotes(e.data.notes); if(e.data.gaps)setGaps(e.data.gaps); }; return()=>c.close(); },[]);

  function persist(s:Record<string,Status>,n:Notes=notes,g:Task[]=gaps){ setStatuses(s);setNotes(n);setGaps(g); try{ localStorage.setItem(SK,JSON.stringify(s));localStorage.setItem(NK,JSON.stringify(n));localStorage.setItem(GK,JSON.stringify(g));const c=new BroadcastChannel(CK);c.postMessage({type:"state",statuses:s,notes:n,gaps:g});c.close(); }catch{} }
  function setStatus(id:string,status:Status){
    const stamp=new Date().toISOString();
    if(status==="green"){
      const evidence=(notes[id]?.evidence||VERIFIED_EVIDENCE[id]||"").trim();
      if(!evidence){
        persist({...statuses,[id]:"yellow"},{...notes,[id]:{...notes[id],blocker:"GREEN блокиран: добави Evidence (URL / commit / test result).",updatedAt:stamp}});
        return;
      }
      if(id.startsWith(`${FINAL_PHASE}.`)){
        const blockers=phases.filter(p=>p.id!==FINAL_PHASE).flatMap(p=>p.tasks).filter(t=>(statuses[t.id]||t.defaultStatus)!=="green");
        if(blockers.length){
          persist({...statuses,[id]:"yellow"},{...notes,[id]:{...notes[id],blocker:`FINAL GREEN блокиран: ${blockers.length} точки извън Етап ${FINAL_PHASE} още не са GREEN.`,updatedAt:stamp}});
          return;
        }
      }
    }
    persist({...statuses,[id]:status},{...notes,[id]:{...notes[id],updatedAt:stamp}});
  }
  function setNote(id:string,field:"evidence"|"blocker",value:string){ persist(statuses,{...notes,[id]:{...notes[id],[field]:value,updatedAt:new Date().toISOString()}}); }
  function addGap(){ const label=gapText.trim();if(!label)return;const id=`GAP.${Date.now()}`,g:Task={id,label,defaultStatus:"red",kind:"core"};setGapText("");persist({...statuses,[id]:"red"},notes,[...gaps,g]); }

  const all=useMemo(()=>[...phases.flatMap(p=>p.tasks),...gaps],[gaps]);
  const totals=useMemo(()=>{ const x:Record<Status,number>={green:0,yellow:0,red:0};all.forEach(t=>x[statuses[t.id]||t.defaultStatus]++);return x; },[all,statuses]);
  const progress=all.length?Math.round(totals.green/all.length*100):0;
  const next=phases.flatMap(p=>p.tasks).find(t=>(statuses[t.id]||t.defaultStatus)!=="green") || gaps.find(t=>(statuses[t.id]||t.defaultStatus)!=="green");
  const nextPhase=next?phases.find(p=>p.tasks.some(t=>t.id===next.id)):undefined;
  const preFinalOpen=useMemo(()=>phases.filter(p=>p.id!==FINAL_PHASE).flatMap(p=>p.tasks).filter(t=>(statuses[t.id]||t.defaultStatus)!=="green").length,[statuses]);
  const visible=useMemo(()=>{ const q=query.trim().toLowerCase(), src:Phase[]=gaps.length?[...phases,{id:"GAP",title:"Открити пропуски",wave:99,tasks:gaps}]:phases; return src.map(p=>({...p,tasks:p.tasks.filter(t=>{const s=statuses[t.id]||t.defaultStatus;return(filter==="all"||s===filter)&&(!q||`${t.id} ${t.label} ${p.title}`.toLowerCase().includes(q));})})).filter(p=>p.tasks.length); },[gaps,query,filter,statuses]);

  return <>
    <button className="burgerButton" aria-label="Отвори меню" onClick={()=>setMenu(true)}><span/><span/><span/></button>{menu&&<div className="menuShade" onClick={()=>setMenu(false)}/>}<aside className={`sidePanel ${menu?"sideOpen":""}`}><div className="sidePanelTop"><div><div className="miniLabel">ENCHEV AUCTIONS</div><strong>System Command Center</strong></div><button className="iconButton" onClick={()=>setMenu(false)}>×</button></div><button className="sideMenuItem" onClick={()=>{setOpen(true);setMenu(false);}}><span className="sideMenuIcon">◫</span><span><b>Етапи</b><small>Master System Plan v{PLAN_VERSION} + Expansion v{EXPANSION_VERSION} · 0 → 100%</small></span><span>›</span></button><button className="sideMenuItem" onClick={()=>{setDesign2Open(true);setMenu(false);}}><span className="sideMenuIcon">✦</span><span><b>Design Process 2</b><small>World-class mobile + desktop redesign · DAVID</small></span><span>›</span></button><div className="sideStatusBox"><div className="liveLine"><i/> LOCAL REALTIME · CLOUD NEXT</div><span>Системен прогрес</span><b>{progress}%</b><div className="miniProgress"><i style={{width:`${progress}%`}}/></div><small>{totals.green} работят · {totals.yellow} тест/грешка · {totals.red} липсват</small></div></aside>
    {open&&<section className="controlOverlay"><header className="controlHeader"><div><div className="eyebrow">MASTER SYSTEM PLAN v{PLAN_VERSION} + INTERNATIONAL COMPANY EXPANSION v{EXPANSION_VERSION} · SOURCE OF TRUTH · 0 → 100%</div><h1>Enchev Auctions — Етапи</h1><p>Frozen 00–61 остават immutable; append-only 62–99 разширяват системата до реална международна компания: corporate/commercial → payments/tax/customs → logistics/operations → CRM/support → finance/BI → country launch → final operating acceptance.</p></div><button className="closeControl" onClick={()=>setOpen(false)}>×</button></header>
      <div className="controlKpis"><div><span>ПРОГРЕС</span><b>{progress}%</b><small>{all.length} системни точки</small></div><div className="kGreen"><span>РАБОТИ</span><b>{totals.green}</b><small>доказано</small></div><div className="kYellow"><span>ТЕСТ / ГРЕШКА</span><b>{totals.yellow}</b><small>не е приключено</small></div><div className="kRed"><span>ЛИПСВА</span><b>{totals.red}</b><small>не е построено</small></div><div><span>LIVE</span><b className="clockText">{now.toLocaleTimeString("bg-BG")}</b><small>локален realtime</small></div></div>
      <div className="nextGrid"><div className="nextCard"><span>NEXT SYSTEM BLOCKER</span><b>{next?`${next.id} · ${next.label}`:"Всичко е GREEN"}</b></div><div className="nextCard"><span>EXECUTION WAVE</span><b>{nextPhase?`WAVE ${nextPhase.wave} · ${WAVE_LABELS[nextPhase.wave]}`:"FINAL COMPLETE"}</b></div><div className="nextCard"><span>FINAL 100% GATE</span><b>{preFinalOpen===0?"Готов за Етап 47":`${preFinalOpen} точки извън финалния етап остават`}</b></div></div>
      <div className="controlTools"><div className="filterGroup">{(["all","green","yellow","red"] as const).map(v=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{v==="all"?"Всички":v==="green"?"Работи":v==="yellow"?"Тест/грешка":"Липсва"}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Търси функция, тест, етап..."/></div>
      <div className="gapBox"><div><b>Execution model</b><small>Етапните IDs са постоянни. Подреждането е по WAVE, за да следваме зависимости без да преномерираме старите точки. Нови бъдещи открития се добавят append-only като GAP.</small></div><div className="gapInput"><input value={gapText} onChange={e=>setGapText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addGap()} placeholder="Нова липсваща системна стъпка..."/><button onClick={addGap}>Добави GAP</button></div></div>
      <div className="phaseList">{visible.map(p=>{const g=p.tasks.filter(t=>(statuses[t.id]||t.defaultStatus)==="green").length,y=p.tasks.filter(t=>(statuses[t.id]||t.defaultStatus)==="yellow").length,r=p.tasks.length-g-y,pct=Math.round(g/p.tasks.length*100);return <details className={`phaseBlock ${p.id==="GAP"?"gapPhase":""}`} key={p.id} open={p.wave===0||p.id==="01"||p.id==="47"||p.id==="GAP"}><summary className="phaseHead"><div><span>{p.id==="GAP"?"GAP":`WAVE ${p.wave} · ЕТАП ${p.id}`}</span><b>{p.title}</b><small>{p.id==="GAP"?"Append-only discoveries":WAVE_LABELS[p.wave]}</small></div><div className="phaseCounts"><i className="greenDot">{g}</i><i className="yellowDot">{y}</i><i className="redDot">{r}</i><strong>{pct}%</strong></div></summary><div className="phaseTasks">{p.tasks.map(t=>{const st=statuses[t.id]||t.defaultStatus,n=notes[t.id]||{},evidence=n.evidence||VERIFIED_EVIDENCE[t.id]||"";return <article key={t.id} className={`taskCard task-${st}`}><div className="taskTop"><div className="taskMain"><span className="taskId">{t.id}</span>{t.kind!=="core"&&<span className={`kind kind-${t.kind}`}>{t.kind.toUpperCase()}</span>}<b>{t.label}</b><small>{st==="green"?"Работи, проверено е и има evidence":st==="yellow"?"Има тест, грешка, blocker или липсва evidence":"Още не е построено"}</small></div><div className="statusButtons"><button className={st==="green"?"green":""} onClick={()=>setStatus(t.id,"green")}>РАБОТИ</button><button className={st==="yellow"?"yellow":""} onClick={()=>setStatus(t.id,"yellow")}>ТЕСТ/ГРЕШКА</button><button className={st==="red"?"red":""} onClick={()=>setStatus(t.id,"red")}>ЛИПСВА</button></div></div><div className="taskDetails"><input value={evidence} onChange={e=>setNote(t.id,"evidence",e.target.value)} placeholder="Evidence: URL / commit / test result"/><input value={n.blocker||""} onChange={e=>setNote(t.id,"blocker",e.target.value)} placeholder="Грешка / blocker / какво остава"/><span>{n.updatedAt?`Update ${new Date(n.updatedAt).toLocaleString("bg-BG")}`:"No update yet"}</span></div></article>;})}</div></details>;})}</div>
      <footer className="controlFooter"><b>Правило v{PLAN_VERSION}:</b> IDs не се преномерират. Изпълняваме по WAVE, не по цифров номер на етапа. GREEN се допуска само с evidence. Етап 47 не може да стане GREEN, докато всяка друга системна точка не е GREEN. YELLOW = частично/грешка/липсваща проверка; RED = липсва. Бъдещи открития се добавят append-only като GAP.</footer>
    </section>}
    <DesignProcess2 open={design2Open} onClose={()=>setDesign2Open(false)} />
  </>;
}